services:
  - type: web
    name: abpeinturepro
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/public
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
